## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property PACKAGE_PIN W5 [get_ports CLOCK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLOCK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLOCK]
 
## Switches
#set_property PACKAGE_PIN V17 [get_ports {A[0]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
#set_property PACKAGE_PIN V16 [get_ports {A[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
#set_property PACKAGE_PIN W16 [get_ports {A[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
#set_property PACKAGE_PIN W17 [get_ports {A[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
#set_property PACKAGE_PIN W15 [get_ports {B[0]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
#set_property PACKAGE_PIN V15 [get_ports {B[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
#set_property PACKAGE_PIN W14 [get_ports {B[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
#set_property PACKAGE_PIN W13 [get_ports {B[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
#set_property PACKAGE_PIN V2 [get_ports {C[0]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
#set_property PACKAGE_PIN T3 [get_ports {C[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
#set_property PACKAGE_PIN T2 [get_ports {C[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
#set_property PACKAGE_PIN R3 [get_ports {C[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {C[3]}]
#set_property PACKAGE_PIN W2 [get_ports {D[0]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
#set_property PACKAGE_PIN U1 [get_ports {D[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
#set_property PACKAGE_PIN T1 [get_ports {D[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
#set_property PACKAGE_PIN R2 [get_ports {D[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]
 

## LEDs
#set_property PACKAGE_PIN U16 [get_ports {LED}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {LED}]
#set_property PACKAGE_PIN E19 [get_ports {Ynext[1]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[1]}]
#set_property PACKAGE_PIN U19 [get_ports {Ynext[2]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[2]}]
#set_property PACKAGE_PIN V19 [get_ports {Ynext[3]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[3]}]
#set_property PACKAGE_PIN W18 [get_ports {Ynext[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[4]}]
#set_property PACKAGE_PIN U15 [get_ports {Ynext[5]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[5]}]
#set_property PACKAGE_PIN U14 [get_ports {Ynext[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[6]}]
#set_property PACKAGE_PIN V14 [get_ports {Ynext[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[7]}]
#set_property PACKAGE_PIN V13 [get_ports {Ynext[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[8]}]
#set_property PACKAGE_PIN V3 [get_ports {Ynext[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[9]}]
#set_property PACKAGE_PIN W3 [get_ports {Ynext[10]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[10]}]
#set_property PACKAGE_PIN U3 [get_ports {Ynext[11]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[11]}]
#set_property PACKAGE_PIN P3 [get_ports {Ynext[12]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[12]}]
#set_property PACKAGE_PIN N3 [get_ports {Ynext[13]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[13]}]
#set_property PACKAGE_PIN P1 [get_ports {Ynext[14]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[14]}]
#set_property PACKAGE_PIN L1 [get_ports {Ynext[15]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {Ynext[15]}]
	
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {sseg[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[7]}]
set_property PACKAGE_PIN W6 [get_ports {sseg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
set_property PACKAGE_PIN U8 [get_ports {sseg[5]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
set_property PACKAGE_PIN V8 [get_ports {sseg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
set_property PACKAGE_PIN U5 [get_ports {sseg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
set_property PACKAGE_PIN V5 [get_ports {sseg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
set_property PACKAGE_PIN U7 [get_ports {sseg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]

set_property PACKAGE_PIN V7 [get_ports {sseg[0]}]							
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]

set_property PACKAGE_PIN U2 [get_ports {DISP_EN[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DISP_EN[0]}]
set_property PACKAGE_PIN U4 [get_ports {DISP_EN[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DISP_EN[1]}]
set_property PACKAGE_PIN V4 [get_ports {DISP_EN[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DISP_EN[2]}]
set_property PACKAGE_PIN W4 [get_ports {DISP_EN[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {DISP_EN[3]}]


##Buttons
set_property PACKAGE_PIN U18 [get_ports {btn}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {btn}]
set_property PACKAGE_PIN T18 [get_ports {btnU}]						
        set_property IOSTANDARD LVCMOS33 [get_ports {btnU}]
set_property PACKAGE_PIN T17 [get_ports {btn_r}]						
    set_property IOSTANDARD LVCMOS33 [get_ports {btn_r}]